package com.tr.myproject.dal.mybatis.mapper;

import com.tr.myproject.dal.mybatis.model.OrderPO;

import java.util.List;

public interface OrderPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Mar 08 15:32:05 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Mar 08 15:32:05 CST 2019
     */
    int insert(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Mar 08 15:32:05 CST 2019
     */
    OrderPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Mar 08 15:32:05 CST 2019
     */
    List<OrderPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Fri Mar 08 15:32:05 CST 2019
     */
    int updateByPrimaryKey(OrderPO record);
}